adding logging

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -8,7 +8,7 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-echo "ASDF download path $ASDF_DOWNLOAD_PATH"
+echo "Logging: ASDF download path $ASDF_DOWNLOAD_PATH"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 release_file="$ASDF_DOWNLOAD_PATH/bp"
@@ -18,13 +18,13 @@ download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 echo "Logging: I made it this far"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-
-echo "Logging: tar successful, asdf download path: $ASDF_DOWNLOAD_PATH, release file: $release_file"
-ls $release_file
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
-
-echo "Logging: release file removed"
+##  Extract contents of tar.gz file into the download directory
+#tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+#
+#echo "Logging: tar successful, asdf download path: $ASDF_DOWNLOAD_PATH, release file: $release_file"
+#ls $release_file
+#
+## Remove the tar.gz file since we don't need to keep it
+#rm "$release_file"
+#
+#echo "Logging: release file removed"
